SELECT HISTORY_ID, 
IF(DISCOUNT_RATE IS NOT NULL, ROUND((DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE * ((100-DISCOUNT_RATE)/100)), (DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON CASE
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN P.DURATION_TYPE = '90일 이상' AND P.CAR_TYPE = '트럭'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN P.DURATION_TYPE = '30일 이상' AND P.CAR_TYPE = '트럭'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN P.DURATION_TYPE = '7일 이상' AND P.CAR_TYPE = '트럭'
    END
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC
