SELECT HISTORY_ID,  CASE
                    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 0.85)
                    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 0.92)
                    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 0.95)
                    ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)
                    END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC