SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (SELECT ID 
            FROM DEVELOPERS D
            JOIN SKILLCODES S
            ON D.SKILL_CODE & S.CODE
            WHERE S.CATEGORY = 'FRONT END'
            GROUP BY ID)
ORDER BY ID