SELECT 
(SELECT SUM(SCORE)
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
                
FROM HR_EMPLOYEES E
JOIN HR_DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID
WHERE EMP_NO = (SELECT EMP_NO
                FROM HR_GRADE
                GROUP BY EMP_NO
                ORDER BY SUM(SCORE) DESC
                LIMIT 1)



